# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Koffan
version: "2.11.0-5"
slug: koffan
description: Free self-hosted groceries list for families and shared households
url: "https://github.com/borucsan/ha-addons/tree/main/koffan"
ingress: true
ingress_port: 8080
ingress_stream: true
panel_icon: mdi:cart
panel_title: Koffan
arch:
  - aarch64
  - amd64
init: false
ports:
  8080/tcp: 8283
ports_description:
  8080/tcp: Koffan web interface
map:
  - addon_config:rw
options:
  timezone: "UTC"
  default_lang: "en"
  api_token: ""
schema:
  timezone: "str?"
  default_lang: "str?"
  api_token: "str?"
environment:
  TZ: "${timezone}"
  APP_ENV: "production"
  DEFAULT_LANG: "${default_lang}"
  API_TOKEN: "${api_token}"
  DB_PATH: "/data/shopping.db"
