# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Wallos
version: "4.6.2-1"
slug: wallos
description: Open-source personal subscription tracker
url: "https://github.com/borucsan/ha-addons/tree/main/wallos"
ingress: true
ingress_port: 80
panel_icon: mdi:wallet-membership
panel_title: Wallos
arch:
  - aarch64
  - amd64
init: false
ports:
  80/tcp: null
ports_description:
  80/tcp: Wallos web interface (optional)
map:
  - addon_config:rw
options:
  timezone: "UTC"
schema:
  timezone: "str?"
environment:
  TZ: "${timezone}"
