# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/borucsan/mealie-discord-import:sha-2f352bc
  amd64: ghcr.io/borucsan/mealie-discord-import:sha-2f352bc
