# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/actualbudget/actual:26.6.0-alpine"
  amd64: "ghcr.io/actualbudget/actual:26.6.0-alpine"
